cc_library(
    name = "number-func",
    srcs = ["numbers.cpp"],
    visibility = ["//main:__pkg__"],
)

cc_library(
    name = "number-func2",
    srcs = ["numbers2.cpp"],
    visibility = ["//main:__pkg__"],
)